### ISSUE TITLE
"Upload files" has had an error and not added some necessary files.

### ISSUE THREAD

**Issue by foxcqrn** [PugFreedomMod/PugFreedomMod#1]
There has been an error with uploading all of the files with uploading them from GitHub's upload files new feature. I suggest using GitHub Desktop to upload files.

EDIT: Also, I'm not a collaborator anymore?

**Comment by DUFCLiam** [comment]
I need to add you.

**Comment by foxcqrn** [comment]
k

**Comment by DUFCLiam** [comment]
Should be added now.

**Comment by DUFCLiam** [comment]
You are invited to the "Developers" team you are no longer collaborator but have the same permissions as one.

**Comment by DUFCLiam** [comment]
What files are missing?

**Comment by foxcqrn** [comment]
k

**Comment by DUFCLiam** [comment]
Does not matter I am currently fixing the issue.

**Comment by foxcqrn** [comment]
like Commands, Listener, and more folders.

**Comment by foxcqrn** [comment]
https://github.com/PugFreedomMod/PugFreedomMod/tree/master/src/me

**Comment by DUFCLiam** [comment]
I know, I figured when they where missing xD I forgot to even import them in the first place. xD

**Comment by foxcqrn** [comment]
lol
