### ISSUE TITLE
Website Problem

### ISSUE THREAD

**Issue by foxcqrn** [PugFreedomMod/PugFreedomMod#3]
The website "https://officialpugfreedom.boards.net/" does not work..

**Comment by rovertdude** [comment]
The main forums is pugfreedommod.boards.net

**Comment by foxcqrn** [comment]
Alright.

**Comment by foxcqrn** [comment]
Requesting another Collaborator invite email thing. I deleted my emails.

**Comment by DUFCLiam** [comment]
You do not need it, You already have the rank :) @FoxIshDaBest

**Comment by foxcqrn** [comment]
@DUFCLiam k. Didn't notice
