### ISSUE TITLE
Collab Help

### ISSUE THREAD

**Issue by foxcqrn** [PugFreedomMod/PugFreedomMod#4]
Still, when I try to contribute to the repository, it tells me, 

"You’re creating a file in a project you don’t have write access to. We’ve created a fork of this project for you to commit your proposed changes to. Submitting a change will create the file in a new branch in your fork, so you can send a pull request."

**Comment by DUFCLiam** [comment]
You will have permission this weekend but please make Prs

**Comment by DUFCLiam** [comment]
Issue fixed, you where on read permissions

**Comment by foxcqrn** [comment]
Oh. Yeah now I can add Labels and files

**Comment by DUFCLiam** [comment]
You're welcome ;) @FoxIshDaBest

**Comment by DUFCLiam** [comment]
@FoxIshDaBest Did you add the complete label?

**Comment by DUFCLiam** [comment]
Nvm I changed the label name

**Comment by foxcqrn** [comment]
no lol
