### ISSUE TITLE
[FIXED]

### ISSUE THREAD

**Issue by JeromSar** [PugFreedomMod/PugFreedomMod#7]
[SNIP]

**Comment by FoxIshDaBest** [comment]
I fixed the TFM_Util stuffs

**Comment by JeromSar** [comment]
@FoxIshDaBest In this case, there is another problem. The project's license was removed.

**Comment by AvalancheYT** [comment]
@JeromSar, the license have moved into a folder - https://github.com/PugFreedomMod/PugFreedomMod/blob/master/.github/LICENCE.md

**Comment by JeromSar** [comment]
@AvalancheYT That would be considered 'hiding' the license. Additionally, it does not make sense to put the license in a folder considering the license has nothing to do with Github.

**Comment by AvalancheYT** [comment]
@JeromSar, I will fix this.
